# Generated by Django 4.2.1 on 2023-05-10 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 19, 28, 19, 27651, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
