# Generated by Django 4.2.1 on 2023-05-11 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_note_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 14, 51, 31, 103095, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
